### ISSUE TITLE
:date_long is not rendering any date

### ISSUE THREAD

**Issue by toptens** [gethugothemes/geeky-hugo#3]
![Screenshot from 2021-09-24 09-56-33](https://user-images.githubusercontent.com/91243892/134615971-d95128c9-8db4-4838-8534-ee56dd6d3890.png)

Please see this problem, how can i solve this ?

**Comment by somratpro** [comment]
Hello @toptens 

Thanks for using Geeky Hugo. To fix this issue, you need to use minimum Hugo v0.88.0. Then it will render correctly. Also if you like this template, A star to the repository would be amazing.
