### ISSUE TITLE
Markdown Syntax (Ordered/Unordered Lists) are not working

### ISSUE THREAD

**Issue by imnileshd** [gethugothemes/geeky-hugo#6]
Hello,

I tried writing some basic  markdown syntax like (Ordered/Unordered Lists) but it is not showing correct output, Can please help me to resolve this?

Markdown Syntax - 
1. First item
2. Second item
3. Third item
4. Fourth item

Expected Output - 
1. First item
2. Second item
3. Third item
4. Fourth item

But rendering like -
First item
Second item
Third item
Fourth item

Thanks,
Nilesh

**Comment by tfsomrat** [comment]
Hello @imnileshd 

Thanks for your concern. I have added the style. please download the latest code. 

If you like this theme, a star to the repository would be most appreciated.

**Comment by imnileshd** [comment]
Hello @tfsomrat 
Thanks for instant help. I will try with latest style. 

And I really like this theme. 

Thanks Again.

**Comment by imnileshd** [comment]
Above is resolved and now affecting here. please check this.
![image](https://user-images.githubusercontent.com/79582180/143828404-b6f59782-36ba-4252-98a5-41a3c9a0d387.png)

**Comment by tfsomrat** [comment]
Thanks for letting me know about this. it has been fixed now.
