### ISSUE TITLE
More than one category causes layout problem

### ISSUE THREAD

**Issue by ssindelar** [gethugothemes/geeky-hugo#7]
When adding more than one category to a post, the displayed categories overlap.

I guess they should be displayed in a row but they are all left aligned an overlap each other.

Steps to reproduce:
1. Just add a second category to a post

**Comment by tfsomrat** [comment]
Hello @ssindelar 

Thanks for your concern. this issue has been fixed. please download the latest version of the theme. Also if you like this theme, a star to the repository would be amazing.
