### ISSUE TITLE
forestry Error building site 

### ISSUE THREAD

**Issue by pacutlie** [gethugothemes/geeky-hugo#8]
Installing Hugo 0.81.0
Start building sites … 
ERROR 2021/12/27 17:09:10 render of "home" failed: execute of template failed: template: index.html:44:4: executing "index.html" at <partial "footer.html" .>: error calling partial: "/srv/layouts/partials/footer.html:2:64": execute of template failed: template: partials/footer.html:2:64: executing "partials/footer.html" at <$bgImage.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/27 17:09:10 render of "taxonomy" failed: execute of template failed: template: _default/terms.html:44:4: executing "_default/terms.html" at <partial "footer.html" .>: error calling partial: "/srv/layouts/partials/footer.html:2:64": execute of template failed: template: partials/footer.html:2:64: executing "partials/footer.html" at <$bgImage.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 478 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: _default/terms.html:44:4: executing "_default/terms.html" at <partial "footer.html" .>: error calling partial: "/srv/layouts/partials/footer.html:2:64": execute of template failed: template: partials/footer.html:2:64: executing "partials/footer.html" at <$bgImage.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink

**Comment by tfsomrat** [comment]
Hello @pacutlie 

I am sorry for you are having trouble with our theme. Actually, you can't deploy this site with forestry for now. We are using so many Hugo Pipes to get the best performance. So you need to deploy this theme with Netlify for now. If we could find out any way to deploy with forestry, we will update this theme. Thanks
